#!/bin/bash
#ref of command awk: https://ubuntuforums.org/showthread.php?t=840054
set -e

INPUTDIR="/wk_cms2/youying/public/2017_94X_3_1_X_and_3_2_0"
OUTPUTDIR="/home/ykao/legacy/CMSSW_9_4_10/src/t2cH/plots"

#touch $OUTPUTDIR/log
#./clear
#./mkplotdir
for file in `cat ListRootFiles | grep -v "#"`
do
    echo "MESSAGE: Start to analyze ${file}"
    echo $file | awk -F "." '{print "'$INPUTDIR'""/"$1".root", "'$OUTPUTDIR'""/"$1"/hist_"$1".root", $1, "'$OUTPUTDIR'""/"$1}' | xargs -n4 ./bin/runner 
    # REMARK: input_file / output_file / datasets / output_dir
done

