#!/bin/bash
#ref of command awk: https://ubuntuforums.org/showthread.php?t=840054
set -e

INPUTDIR="ntuples_skimmed"
OUTPUTDIR="plots"
EXECUTABLE=./bin/selection

ExeAnalysis(){
    file=$1
    log=log/log_skimmed_ntuple_${file}.txt
    echo "[MESSAGE] Start to analyze ${file}" | tee ${log} 
    echo $file | awk -F "." '{print "'$INPUTDIR'""/ntuple_"$1".root", "'$OUTPUTDIR'""/"$1"/hist_"$1".root", $1, "'$OUTPUTDIR'""/"$1}' |\
    xargs -n4 ${EXECUTABLE} | grep -v ientry | tee -a ${log}
    # REMARK: input_file / output_file / datasets / output_dir
}


#--------------- Setup ---------------#
echo "[MESSAGE] Check directories for plots..." && ./script/mkplotdir
echo "[MESSAGE] Check executable..." && make
echo "[MESSAGE] Ready!"

#--------------- DryRun ---------------#
if [[ $1 == '-d' || '--dryRun' ]]; then
    ExeAnalysis ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8.root
    echo "[MESSAGE] This is the end of dryRun execution." && exit 1
fi

#--------------- TT Signal ---------------#
ExeAnalysis TT_FCNC-TtoHJ_aThadronic_HToaa_eta_hct-MadGraph5-pythia8.root
ExeAnalysis TT_FCNC-TtoHJ_aThadronic_HToaa_eta_hut-MadGraph5-pythia8.root
ExeAnalysis TT_FCNC-TtoHJ_aTleptonic_HToaa_eta_hct-MadGraph5-pythia8.root
ExeAnalysis TT_FCNC-TtoHJ_aTleptonic_HToaa_eta_hut-MadGraph5-pythia8.root
ExeAnalysis TT_FCNC-aTtoHJ_Thadronic_HToaa_eta_hct-MadGraph5-pythia8.root
ExeAnalysis TT_FCNC-aTtoHJ_Thadronic_HToaa_eta_hut-MadGraph5-pythia8.root
ExeAnalysis TT_FCNC-aTtoHJ_Tleptonic_HToaa_eta_hct-MadGraph5-pythia8.root
ExeAnalysis TT_FCNC-aTtoHJ_Tleptonic_HToaa_eta_hut-MadGraph5-pythia8.root
#--------------- Data ---------------#
ExeAnalysis DoubleEG_B.root
ExeAnalysis DoubleEG_C.root
ExeAnalysis DoubleEG_D.root
ExeAnalysis DoubleEG_E.root
ExeAnalysis DoubleEG_F.root
#--------------- Resonant bkg ---------------#
ExeAnalysis GluGluHToGG_M125_13TeV_amcatnloFXFX_pythia8.root
ExeAnalysis VBFHToGG_M125_13TeV_amcatnlo_pythia8.root
ExeAnalysis VHToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8.root
ExeAnalysis ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8.root
#--------------- non-Resonant bkg ---------------#
ExeAnalysis DiPhotonJetsBox_M40_80-Sherpa.root
ExeAnalysis GJet_Pt-20to40_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8.root
ExeAnalysis GJet_Pt-20toInf_DoubleEMEnriched_MGG-40to80_TuneCP5_13TeV_Pythia8.root
ExeAnalysis QCD_Pt-30to40_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8.root
ExeAnalysis QCD_Pt-30toInf_DoubleEMEnriched_MGG-40to80_TuneCP5_13TeV_Pythia8.root
ExeAnalysis QCD_Pt-40toInf_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8.root
ExeAnalysis TGJets_TuneCP5_13TeV_amcatnlo_madspin_pythia8.root
ExeAnalysis TTGG_0Jets_TuneCP5_13TeV_amcatnlo_madspin_pythia8.root
ExeAnalysis TTGJets_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8.root
#--------------- non-Resonant bkg (multi root files) ---------------#
ExeAnalysis DiPhotonJetsBox_MGG-80toInf_13TeV-Sherpa.root
ExeAnalysis GJet_Pt-40toInf_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8.root
#--------------- ST Signal ---------------#
ExeAnalysis ST_FCNC-TH_Thadronic_HToaa_eta_hct-MadGraph5-pythia8.root
ExeAnalysis ST_FCNC-TH_Tleptonic_HToaa_eta_hct-MadGraph5-pythia8.root
ExeAnalysis ST_FCNC-TH_Thadronic_HToaa_eta_hut-MadGraph5-pythia8.root
ExeAnalysis ST_FCNC-TH_Tleptonic_HToaa_eta_hut-MadGraph5-pythia8.root
echo "[MESSAGE] This is the end of execution." && exit 0
