#!/bin/bash
#ref of command awk: https://ubuntuforums.org/showthread.php?t=840054
set -e

INPUTDIR="/wk_cms2/youying/public/RunII2016_8028_flashgg_ntuples"
OUTPUTDIR="ntuples_skimmed"
EXECUTABLE=./bin/preselection
#EXECUTABLE=echo


ExeAnalysis(){
    file=$1
    log=log/log_${file}.txt
    echo "[MESSAGE] Start to analyze ${file}" | tee ${log} 
    echo $file | awk -F "." '{print "'$INPUTDIR'""/"$1, "'$OUTPUTDIR'""/ntuple_"$1".root", $1}' |\
    xargs -n3 ${EXECUTABLE} | grep -v ientry | tee -a ${log}
    # REMARK: input_file / output_file / datasets
}

#--------------- Setup ---------------#
echo "[MESSAGE] Check directories for plots..." && ./script/mkplotdir
echo "[MESSAGE] Check executable..." && make
echo "[MESSAGE] Ready!"

#--------------- DryRun ---------------#
if [[ $1 == '-d' || $1 == '--dryRun' ]]; then
    ExeAnalysis DoubleEG_sethzenz-LegacyReReco-07Aug2017-2_6_1-2_6_1-v1-Run2016B-07Aug17_ver2-v2
    #ExeAnalysis QCD_Pt-40toInf_DoubleEMEnriched_MGG-80toInf_TuneCUETP8M1_13TeV_Pythia8
    #ExeAnalysis ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8
    echo "[MESSAGE] This is the end of dryRun execution." && exit 0
fi

#--------------- TT Signal ---------------#
#--------------- ST Signal ---------------#
#--------------- Data ---------------#
ExeAnalysis DoubleEG_sethzenz-LegacyReReco-07Aug2017-2_6_1-2_6_1-v0-Run2016B-07Aug17_ver2-v2
ExeAnalysis DoubleEG_sethzenz-LegacyReReco-07Aug2017-2_6_1-2_6_1-v0-Run2016C-07Aug17-v1
ExeAnalysis DoubleEG_sethzenz-LegacyReReco-07Aug2017-2_6_1-2_6_1-v0-Run2016D-07Aug17-v1
ExeAnalysis DoubleEG_sethzenz-LegacyReReco-07Aug2017-2_6_1-2_6_1-v0-Run2016E-07Aug17-v1
ExeAnalysis DoubleEG_sethzenz-LegacyReReco-07Aug2017-2_6_1-2_6_1-v0-Run2016F-07Aug17-v1
ExeAnalysis DoubleEG_sethzenz-LegacyReReco-07Aug2017-2_6_1-2_6_1-v0-Run2016G-07Aug17-v1
ExeAnalysis DoubleEG_sethzenz-LegacyReReco-07Aug2017-2_6_1-2_6_1-v0-Run2016H-07Aug17-v1
ExeAnalysis DoubleEG_sethzenz-LegacyReReco-07Aug2017-2_6_1-2_6_1-v1-Run2016B-07Aug17_ver2-v2
ExeAnalysis DoubleEG_sethzenz-LegacyReReco-07Aug2017-2_6_1-2_6_1-v1-Run2016C-07Aug17-v1
ExeAnalysis DoubleEG_sethzenz-LegacyReReco-07Aug2017-2_6_1-2_6_1-v1-Run2016D-07Aug17-v1
ExeAnalysis DoubleEG_sethzenz-LegacyReReco-07Aug2017-2_6_1-2_6_1-v1-Run2016E-07Aug17-v1
ExeAnalysis DoubleEG_sethzenz-LegacyReReco-07Aug2017-2_6_1-2_6_1-v1-Run2016F-07Aug17-v1
ExeAnalysis DoubleEG_sethzenz-LegacyReReco-07Aug2017-2_6_1-2_6_1-v1-Run2016G-07Aug17-v1
ExeAnalysis DoubleEG_sethzenz-LegacyReReco-07Aug2017-2_6_1-2_6_1-v1-Run2016H-07Aug17-v1
#--------------- Resonant bkg ---------------#
ExeAnalysis GluGluHToGG_M125_13TeV_amcatnloFXFX_pythia8
ExeAnalysis VBFHToGG_M125_13TeV_amcatnlo_pythia8
ExeAnalysis VHToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8
ExeAnalysis ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8
#--------------- non-Resonant bkg ---------------#
#ExeAnalysis DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8
ExeAnalysis DiPhotonJetsBox_MGG-80toInf_13TeV-Sherpa
ExeAnalysis GJet_Pt-20to40_DoubleEMEnriched_MGG-80toInf_TuneCUETP8M1_13TeV_Pythia8
ExeAnalysis GJet_Pt-20toInf_DoubleEMEnriched_MGG-40to80_TuneCUETP8M1_13TeV_Pythia8
ExeAnalysis GJet_Pt-40toInf_DoubleEMEnriched_MGG-80toInf_TuneCUETP8M1_13TeV_Pythia8
ExeAnalysis QCD_Pt-30to40_DoubleEMEnriched_MGG-80toInf_TuneCUETP8M1_13TeV_Pythia8
ExeAnalysis QCD_Pt-30toInf_DoubleEMEnriched_MGG-40to80_TuneCUETP8M1_13TeV_Pythia8
ExeAnalysis QCD_Pt-40toInf_DoubleEMEnriched_MGG-80toInf_TuneCUETP8M1_13TeV_Pythia8
ExeAnalysis TGJets_TuneCUETP8M1_13TeV_amcatnlo_madspin_pythia8
ExeAnalysis TTGG_0Jets_TuneCUETP8M1_13TeV_amcatnlo_madspin_pythia8
ExeAnalysis TTGJets_TuneCUETP8M1_13TeV-amcatnloFXFX-madspin-pythia8
#ExeAnalysis TTJets_TuneCUETP8M2T4_13TeV-amcatnloFXFX-pythia8
#ExeAnalysis WGToLNuG_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8
#ExeAnalysis WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
#ExeAnalysis WW_TuneCUETP8M1_13TeV-pythia8
#ExeAnalysis WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8
#ExeAnalysis ZGTo2LG_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8
#ExeAnalysis ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8
echo "[MESSAGE] This is the end of execution." && exit 0
