#!/bin/bash
set -e
for file in `cat ListRootFiles | grep -v "#"`
do
    DIRECTORY=plots/"`echo $file | awk -F "." '{print $1}'`"
    if [ ! -d "${DIRECTORY}" ]; then
        mkdir ${DIRECTORY}
    fi
done
