#!/bin/bash
set -e

log=reviewEntries/log_calculation
echo "\"\"\"=== Result of data ===\"\"\"" | tee ${log}
for type in "Individual" "Successive"
do
    for number in "Entries" "Yields"
    do
        for case in "NoCut" "Cut00" "Cut01" "Cut02" "Cut03" "Cut04" "Cut05"
        do
            parameter="${type}_${number}_${case}";
            #------- data -------#
            #cat reviewEntries/log_check_? | grep ${type} | grep ${number}| grep ${case} | awk '{print "'${parameter}'_"NR"="$6}' | tee -a ${log}
            #echo "${parameter}_sum=\$((${parameter}_1 + ${parameter}_2 + ${parameter}_3 + ${parameter}_4 + ${parameter}_5))" | tee -a ${log}
            #echo "echo ${parameter}=\$${parameter}_sum" | tee -a ${log}
            #echo "" | tee -a ${log}
            #------- QCD -------#
            #for file in `ls reviewEntries/log_check_QCD_*`; do $((count+1)); echo ${file} $count; done
            echo "${parameter} = \\" | tee -a ${log}
            cat reviewEntries/log_check_QCD_* | grep ${type} | grep ${number}| grep ${case} | awk '{print $6" +\\"}' | tee -a ${log}
            echo "0" | tee -a ${log}
            echo "print \"${parameter} = %f\" % ${parameter}" | tee -a ${log}
            #echo "echo ${parameter}=\$${parameter}_sum" | tee -a ${log}
            #echo "" | tee -a ${log}
        done
    done
done

chmod +x ${log}
python ${log}
