#!/bin/bash
set -e

log=reviewEntries/log_calculation
#final=reviewEntries/final_result.txt
final=reviewEntries/tmp.txt

# dataset{{{
array=(\
#DYJetsToLL \
#DiPhotonJetsBox \
DoubleEG \
#GJet \
#GluGluHToGG \
#QCD \
#TGJets \
#TTGG \
#TTGJets \
#TTJets \
#TT \
#VBFHToGG \
#VHToGG \
#WGToLNuG \
#WJetsToLNu \
#WW \
#WZTo2L2Q \
#ZGToLLG \
#ZZTo2L2Q \
#ttHJetToGG \
)
#}}}

#echo ${#array[@]} #number of elements in an array

function summary(){
    dataset=$1
    parameter=$2
    output=$3
    number=$4
    echo "${parameter} = \\" >> ${output}
    cat reviewEntries/log_${dataset}* | grep ${type} | grep ${number}| grep ${case} | awk '{print $6" +\\"}' >> ${output}
    echo "0" >> ${output}
    if [ ${number} == "Entries" ]; then echo "print \"${parameter} = %.0f\" % ${parameter}" >> ${output}; fi
    if [ ${number} == "Yields" ];  then echo "print \"${parameter} = %.3f\" % ${parameter}" >> ${output}; fi
}


for dataset in `echo "${array[*]}"`;
do
    output=${log}_${dataset}
    echo "\"\"\"=== Result of ${dataset} ===\"\"\"" > ${output}
    echo "print \"| ${dataset} | NTU | NTU \"" >> ${output}
    for type in "Individual" "Successive"
    do
        for number in "Entries" "Yields"
        do
            for case in "NoCut" "Cut00" "Cut01" "Cut02" "Cut03" "Cut04" "Cut05"
            do
                parameter="${type}_${number}_${case}"
                summary ${dataset} ${parameter} ${output} ${number}
            done
        done
    done
    chmod +x ${output}
done

echo "" > ${final}
for type in "Individual" "Successive"
do
    for number in "Entries" "Yields"
    do
        echo ${type} " | " ${number} | tee -a ${final}
        for dataset in `echo "${array[*]}"`;
        #for script in `ls ${log}_*` 
        do
            script=${log}_${dataset} 
            python ${script} | egrep "NTU|${type}" | egrep "NTU|${number}" | awk '{if(NR==1) print $0; else if(NR==8) print "| " $3 " |"; else print "| "$3;}' | xargs | tee -a ${final}
        done
    done
done
