#!/bin/bash
set -e

if [ ! -d reviewEntries ]; then mkdir reviewEntries; fi

INPUTDIR="/wk_cms2/youying/public/2017_94X_3_1_X_and_3_2_0"
INPUTDIR_ywk="/wk_cms2/ykao/public/2017_94X_3_1_X_and_3_2_0"
OUTPUTDIR="reviewEntries"
EXECUTABLE=./bin/check

# functions{{{
ExeAnalysis(){
    dataset=$1
    log=${OUTPUTDIR}/log_${dataset}.txt
    echo "[MESSAGE] Start to analyze ${dataset}" | tee ${log} 
    echo $dataset | awk -F "." '{print "'$INPUTDIR'""/"$1".root", $1}' | xargs -n2 ${EXECUTABLE} | tee -a ${log}
    # REMARK: input_dataset / datasets 
}
ExeAnalysis_multi(){
    dataset=$1
    log=${OUTPUTDIR}/log_${dataset}.txt
    echo "[MESSAGE] Start to analyze ${dataset}" | tee ${log} 
    echo $dataset | awk -F "." '{print "'$INPUTDIR_ywk'""/"$1, $1}' | xargs -n2 ${EXECUTABLE} | tee -a ${log}
    # REMARK: input_dataset / datasets 
}
ExeAnalysis_singletop(){
    dataset=$1
    log=log/log_${dataset}.txt
    echo "[MESSAGE] Start to analyze ${dataset}" | tee ${log} 
    echo $dataset | awk -F "." '{print "'$INPUTDIR_ywk'""/"$1".root", $1}' | xargs -n2 ${EXECUTABLE} | tee -a ${log}
    # REMARK: input_dataset / datasets 
}
#}}}

FILE=$1
#FILE="ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8.root"
#FILE='TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8'
if [[
      $FILE == 'DiPhotonJetsBox_MGG-80toInf_13TeV-Sherpa' ||
      $FILE == 'GJet_Pt-40toInf_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8' ||
      $FILE == 'TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8' ||
      $FILE == 'DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8' ||
      $FILE == 'WGToLNuG_01J_5f_TuneCP5_13TeV-amcatnloFXFX-pythia8' ||
      $FILE == 'WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8' ||
      $FILE == 'WW_TuneCP5_13TeV-pythia8' ||
      $FILE == 'WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8' ||
      $FILE == 'ZGToLLG_01J_5f_TuneCP5_13TeV-amcatnloFXFX-pythia8' ||
      $FILE == 'ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8'
   ]]; then
    ExeAnalysis_multi $FILE;
    echo "[MESSAGE] This is the end of $FILE" && exit 0
elif [[
        $FILE == 'ST_FCNC-TH_Thadronic_HToaa_eta_hct-MadGraph5-pythia8.root' ||\
        $FILE == 'ST_FCNC-TH_Tleptonic_HToaa_eta_hct-MadGraph5-pythia8.root' ||\
        $FILE == 'ST_FCNC-TH_Thadronic_HToaa_eta_hut-MadGraph5-pythia8.root' ||\
        $FILE == 'ST_FCNC-TH_Tleptonic_HToaa_eta_hut-MadGraph5-pythia8.root'
     ]]; then
    ExeAnalysis_singletop $FILE;
    echo "[MESSAGE] This is the end of $FILE" && exit 0
else
    ExeAnalysis $FILE;
    echo "[MESSAGE] This is the end of $FILE" && exit 0
fi 

# past {{{
#/wk_cms2/ykao/public/2017_94X_3_1_X_and_3_2_0
#TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8

#time ./bin/check "/wk_cms2/ykao/public/2017_94X_3_1_X_and_3_2_0/TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8" \
#"TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8" | tee reviewEntries/log_check_TTJets

#time ./bin/check "/wk_cms2/youying/public/2017_94X_3_1_X_and_3_2_0/ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8.root" \
#"ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8" | tee reviewEntries/log_check_ttH

#ssh node06 "source /cvmfs/cms.cern.ch/cmsset_default.sh; cd /wk_cms2/ykao/CMSSW_9_4_10/src/2017/tqHGG; pwd; eval `scramv1 runtime -sh` \
#time ./bin/check \"/wk_cms2/youying/public/2017_94X_3_1_X_and_3_2_0/QCD_Pt-30to40_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8.root\" \
#\"QCD_Pt-30to40_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8\" | tee reviewEntries/log_check_QCD_Pt-30to40" &
#    
#ssh node07 "source /cvmfs/cms.cern.ch/cmsset_default.sh; cd /wk_cms2/ykao/CMSSW_9_4_10/src/2017/tqHGG; pwd; eval `scramv1 runtime -sh` \
#time ./bin/check \"/wk_cms2/youying/public/2017_94X_3_1_X_and_3_2_0/QCD_Pt-30toInf_DoubleEMEnriched_MGG-40to80_TuneCP5_13TeV_Pythia8.root\" \
#\"QCD_Pt-30toInf_DoubleEMEnriched_MGG-40to80_TuneCP5_13TeV_Pythia8\" | tee reviewEntries/log_check_QCD_Pt-30toInf" &
#
#ssh node08 "source /cvmfs/cms.cern.ch/cmsset_default.sh; cd /wk_cms2/ykao/CMSSW_9_4_10/src/2017/tqHGG; pwd; eval `scramv1 runtime -sh` \
#time ./bin/check \"/wk_cms2/youying/public/2017_94X_3_1_X_and_3_2_0/QCD_Pt-40toInf_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8.root\" \
#\"QCD_Pt-40toInf_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8\" | tee reviewEntries/log_check_QCD_Pt-40toInf" &
#
#
#
#ssh node01 "source /cvmfs/cms.cern.ch/cmsset_default.sh; cd /wk_cms2/ykao/CMSSW_9_4_10/src/2017/tqHGG; pwd; eval `scramv1 runtime -sh` \
#time ./bin/check \"/wk_cms2/youying/public/2017_94X_3_1_X_and_3_2_0/DoubleEG_B.root\" \
#\"DoubleEG_B\" | tee reviewEntries/log_check_B" &
#    
#ssh node02 "source /cvmfs/cms.cern.ch/cmsset_default.sh; cd /wk_cms2/ykao/CMSSW_9_4_10/src/2017/tqHGG; pwd; eval `scramv1 runtime -sh` \
#time ./bin/check \"/wk_cms2/youying/public/2017_94X_3_1_X_and_3_2_0/DoubleEG_C.root\" \
#\"DoubleEG_C\" | tee reviewEntries/log_check_C" &
#
#ssh node03 "source /cvmfs/cms.cern.ch/cmsset_default.sh; cd /wk_cms2/ykao/CMSSW_9_4_10/src/2017/tqHGG; pwd; eval `scramv1 runtime -sh` \
#time ./bin/check \"/wk_cms2/youying/public/2017_94X_3_1_X_and_3_2_0/DoubleEG_D.root\" \
#\"DoubleEG_D\" | tee reviewEntries/log_check_D" &
#
#ssh node04 "source /cvmfs/cms.cern.ch/cmsset_default.sh; cd /wk_cms2/ykao/CMSSW_9_4_10/src/2017/tqHGG; pwd; eval `scramv1 runtime -sh` \
#time ./bin/check \"/wk_cms2/youying/public/2017_94X_3_1_X_and_3_2_0/DoubleEG_E.root\" \
#\"DoubleEG_E\" | tee reviewEntries/log_check_E" &
#
#ssh node05 "source /cvmfs/cms.cern.ch/cmsset_default.sh; cd /wk_cms2/ykao/CMSSW_9_4_10/src/2017/tqHGG; pwd; eval `scramv1 runtime -sh` \
#time ./bin/check \"/wk_cms2/youying/public/2017_94X_3_1_X_and_3_2_0/DoubleEG_F.root\" \
#\"DoubleEG_F\" | tee reviewEntries/log_check_F" &
#}}}
