#!/bin/bash
set -e

time ./bin/check "/wk_cms2/youying/public/2017_94X_3_1_X_and_3_2_0/ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8.root" | tee log_check_ttH

#ssh node01 "source /cvmfs/cms.cern.ch/cmsset_default.sh; cd /wk_cms2/ykao/CMSSW_9_4_10/src/2017/tqHGG; pwd; eval `scramv1 runtime -sh` \
#time ./bin/check \"/wk_cms2/youying/public/2017_94X_3_1_X_and_3_2_0/QCD_Pt-30to40_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8.root\" | tee log_check_QCD_Pt-30to40" &
#    
#ssh node02 "source /cvmfs/cms.cern.ch/cmsset_default.sh; cd /wk_cms2/ykao/CMSSW_9_4_10/src/2017/tqHGG; pwd; eval `scramv1 runtime -sh` \
#time ./bin/check \"/wk_cms2/youying/public/2017_94X_3_1_X_and_3_2_0/QCD_Pt-30toInf_DoubleEMEnriched_MGG-40to80_TuneCP5_13TeV_Pythia8.root\" | tee log_check_QCD_Pt-30toInf" &
#
#ssh node03 "source /cvmfs/cms.cern.ch/cmsset_default.sh; cd /wk_cms2/ykao/CMSSW_9_4_10/src/2017/tqHGG; pwd; eval `scramv1 runtime -sh` \
#time ./bin/check \"/wk_cms2/youying/public/2017_94X_3_1_X_and_3_2_0/QCD_Pt-40toInf_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8.root\" | tee log_check_QCD_Pt-40toInf" &



#ssh node01 "source /cvmfs/cms.cern.ch/cmsset_default.sh; cd /wk_cms2/ykao/CMSSW_9_4_10/src/2017/tqHGG; pwd; eval `scramv1 runtime -sh` \
#time ./bin/check \"/wk_cms2/youying/public/2017_94X_3_1_X_and_3_2_0/DoubleEG_B.root\" | tee rewiewEntries/log_check_B" &
#    
#ssh node02 "source /cvmfs/cms.cern.ch/cmsset_default.sh; cd /wk_cms2/ykao/CMSSW_9_4_10/src/2017/tqHGG; pwd; eval `scramv1 runtime -sh` \
#time ./bin/check \"/wk_cms2/youying/public/2017_94X_3_1_X_and_3_2_0/DoubleEG_C.root\" | tee rewiewEntries/log_check_C" &
#
#ssh node03 "source /cvmfs/cms.cern.ch/cmsset_default.sh; cd /wk_cms2/ykao/CMSSW_9_4_10/src/2017/tqHGG; pwd; eval `scramv1 runtime -sh` \
#time ./bin/check \"/wk_cms2/youying/public/2017_94X_3_1_X_and_3_2_0/DoubleEG_D.root\" | tee rewiewEntries/log_check_D" &
#
#ssh node04 "source /cvmfs/cms.cern.ch/cmsset_default.sh; cd /wk_cms2/ykao/CMSSW_9_4_10/src/2017/tqHGG; pwd; eval `scramv1 runtime -sh` \
#time ./bin/check \"/wk_cms2/youying/public/2017_94X_3_1_X_and_3_2_0/DoubleEG_E.root\" | tee rewiewEntries/log_check_E" &
#
#ssh node05 "source /cvmfs/cms.cern.ch/cmsset_default.sh; cd /wk_cms2/ykao/CMSSW_9_4_10/src/2017/tqHGG; pwd; eval `scramv1 runtime -sh` \
#time ./bin/check \"/wk_cms2/youying/public/2017_94X_3_1_X_and_3_2_0/DoubleEG_F.root\" | tee rewiewEntries/log_check_F" &
