#!/bin/bash
set -e
#--------------------------------------------------
if [ ! -d bin ]; then
    mkdir bin;
fi
#--------------------------------------------------
if [ ! -d ntuples_skimmed ]; then
    mkdir ntuples_skimmed;
fi
#--------------------------------------------------
#if [ ! -d ntuples_pustudy ]; then
#    mkdir ntuples_pustudy;
#fi
#--------------------------------------------------
if [ ! -d plots ]; then
    mkdir plots;
fi
for file in `cat ListRootFiles | grep -v "#"`
do
    DIRECTORY=plots/"`echo $file | awk -F "." '{print $1}'`"
    if [ ! -d "${DIRECTORY}" ]; then
        mkdir ${DIRECTORY}
    fi
done
#--------------------------------------------------
if [ ! -d log ]; then
    mkdir log;
fi

echo "[MESSAGE] Directory are checked and prepared!"
