#!/bin/bash
set -e
function exe(){
    year=$1; dataset=$2; name=`echo $3 | awk 'BEGIN{FS="."}{print $1}'`; #echo ${name}
    root -l -b -q "src/check_ntuples.C(\"${year}\", \"${dataset}\", \"${name}\")"
}

function extractMGG(){
    dataset=$2; name=$1;
    #echo ${dataset}
    root -l -b -q "src/check_ntuples.C(\"${dataset}\", \"${name}\")"
}

#--- stage: calculate totalGenweight ---#
path_17old="/wk_cms2/youying/public/2017_94X_3_1_X_and_3_2_0"
path_16="/wk_cms2/ykao/public/thFCNC/flashgg_105X/2016"
path_17="/wk_cms2/youying/public/thFCNC/flashgg_105X/2017"
path_18="/wk_cms2/youying/public/thFCNC/flashgg_105X/2018"

path=${path_17}; year="2017"; #mkdir -p test/${year};
log=test/totalGenweight_${year}_${tag}.log; #echo ${year} > ${log};

## multi files (totalGenweight){{{
#tag=6
#path=${path_17}; year="2017"; #mkdir -p test/${year};
#log=test/totalGenweight_${year}_${tag}.log; #echo ${year} > ${log};
#path=/wk_cms2/youying/public/thFCNC/flashgg_105X/2017/DiPhotonJetsBox_MGG-80toInf_13TeV-Sherpa
#name=DiPhotonJetsBox_MGG-80toInf_13TeV-Sherpa
#for num in {0..99}
#for num in {100..199}
#for num in {200..299}
#for num in {300..399}
#for num in {400..459}
#for num in {460..517}
#do
#    file=${path}/output${num}.root
#    #echo ${file}
#    exe ${year} ${file} ${name}_${num}.root | tee -a ${log};
#done
#}}}
## extract totalGenweight{{{
#path=${path_17}; year="2017"; #mkdir -p test/${year};
#log=test/totalGenweight_${year}.log; echo ${year} > ${log};
#for entry in `ls ${path}`
#do
#    file=${path}/${entry}
#    if [ ! -d ${file} ]; then
#        exe ${year} ${file} ${entry} | tee -a ${log};
#    else
#        echo "${file} is a directory." | tee -a ${log};
#        for sub_entry in `ls ${file}`;
#        do
#            sub_file=${file}/${sub_entry}
#            exe ${year} ${sub_file} ${sub_entry} | tee -a ${log};
#        done
#    fi
#done
##}}}
# # extract totalGenweight of multifiles{{{
##for year in 2016 2017 2018; do
#year=2017
#for tag in {1..6}; do
#    log=test/totalGenweight_${year}_${tag}.log
#    txt=include/totalGenweight_${year}.txt
#    cat ${log} | grep "${year}" | grep -v "Processing" | grep ":" >> ${txt}
#done
#}}}
## the class of all the new root files are consistent{{{
## stage1: create class file
#for entry in `ls ${path}`
#do
#    file=${path}/${entry}
#    if [ -d ${file} ]; then tag="directory"; else tag="rootfile"; fi
#    if [[ ${tag} != "directory" ]]; then exe ${year} ${file} ${entry}; fi
#    #if [[ ${tag} == "directory" ]]; then echo "${file} is a directory."; ls ${file}; fi
#done

## stage2: rm redundant lines && do comparison
##for year in 2016 2017 2018; do
#for year in "2017old"; do
#    dir=test/${year}
#    log=${dir}/log_${year}
#    num=0
#    rm ${dir}/*.C
#    for entry in `ls ${dir}`
#    do
#        file=${dir}/${entry}
#        name=`echo ${entry} | awk 'BEGIN{FS="."}{print $1}'`
#        sed -i "/${name}/d" ${file}
#        sed -i "/version/d" ${file}
#
#        if [ $num -eq 0 ]; then ref_file=${file}; echo "${ref_file} is ref. file" > ${log}; fi
#        echo ${num} ${name} | tee -a ${log}
#        diff ${ref_file} ${file} | tee -a ${log}
#        num=$((num+1))
#    done
#done
#}}}
## old code{{{
##--------------- Resonant bkg ---------------#
#exe VBFHToGG_M125_13TeV_amcatnlo_pythia8
#exe VHToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8
#exe ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8
#exe GluGluHToGG_M125_13TeV_amcatnloFXFX_pythia8
##--------------- non-Resonant bkg ---------------#
#exe DiPhotonJetsBox_M40_80-Sherpa
#exe GJet_Pt-20to40_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8
#exe GJet_Pt-20toInf_DoubleEMEnriched_MGG-40to80_TuneCP5_13TeV_Pythia8
#exe QCD_Pt-30to40_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8
#exe QCD_Pt-30toInf_DoubleEMEnriched_MGG-40to80_TuneCP5_13TeV_Pythia8
#exe QCD_Pt-40toInf_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8
#exe TGJets_TuneCP5_13TeV_amcatnlo_madspin_pythia8
#exe TTGJets_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8
#exe TTGG_0Jets_TuneCP5_13TeV_amcatnlo_madspin_pythia8
##--------------- non-Resonant bkg (multi-files) ---------------#
#exe DiPhotonJetsBox_MGG-80toInf_13TeV-Sherpa
#exe GJet_Pt-40toInf_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8
#exe TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8
#exe DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8
#exe ZGToLLG_01J_5f_TuneCP5_13TeV-amcatnloFXFX-pythia8
#exe WGToLNuG_01J_5f_TuneCP5_13TeV-amcatnloFXFX-pythia8
#exe WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8
#exe WW_TuneCP5_13TeV-pythia8
#exe WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8
#exe ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8
#
#echo "# of int   = `grep -i npu test/mytree* | grep -ic int`"
#echo "# of float = `grep -i npu test/mytree* | grep -ic float`"
##}}}


#--- stage: check Higgs MGG ---#
extractMGG ttH plots_leptonic/161718/ttH*/hist_ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8.root
extractMGG VBF plots_leptonic/161718/VBF*/hist_VBFHToGG_M125_13TeV_amcatnlo_pythia8.root
extractMGG VH plots_leptonic/161718/VH*/hist_VHToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8.root
extractMGG ggH plots_leptonic/161718/GluGlu*/hist_GluGluHToGG_M125_13TeV_amcatnloFXFX_pythia8.root
