//### AUTOMATICALLY GENERATED BY src/covarianceMatrixStudy.cpp ###//
//### DATASET: /wk_cms2/youying/public/tH_FCNC/Era2017_RR-31Mar2018_v2/TT_FCNC-aTtoHJ_Thadronic_HToaa_eta_hut-MadGraph5-pythia8.root, /wk_cms2/youying/public/tH_FCNC/Era2017_RR-31Mar2018_v2/TT_FCNC-TtoHJ_aThadronic_HToaa_eta_hut-MadGraph5-pythia8.root
#include <TMatrixD.h>


double Chi2_calculator_simple(double w_mass, double t_mass){
    TVectorD vec_mass(2);
    vec_mass(0) = w_mass - w_boson_mass;
    vec_mass(1) = t_mass - top_quark_mass;
    TMatrixD matrix(2,2);
    matrix(0,0) = 344.31; matrix(0,1) =   0.00;
    matrix(1,0) =   0.00; matrix(1,1) = 837.23;
    return matrix.Invert()*vec_mass*vec_mass;
}

double Chi2_calculator_modified(double w_mass, double t_mass){
    TVectorD vec_mass(2);
    vec_mass(0) = w_mass - w_boson_mass;
    vec_mass(1) = t_mass - top_quark_mass;
    TMatrixD matrix(2,2);
    matrix(0,0) = 344.31; matrix(0,1) = 375.30;
    matrix(1,0) = 375.30; matrix(1,1) = 837.23;
    return matrix.Invert()*vec_mass*vec_mass;
}

double Chi2_calculator_improved(double w_mass, double t_mass, double fcnc_top_mass){
    TVectorD vec_mass(3);
    vec_mass(0) = w_mass - w_boson_mass;
    vec_mass(1) = t_mass - top_quark_mass;
    vec_mass(2) = fcnc_top_mass - top_quark_mass;
    TMatrixD matrix(3,3);
    matrix(0,0) = 344.31; matrix(0,1) = 375.30; matrix(0,2) =   7.95;
    matrix(1,0) = 375.30; matrix(1,1) = 837.23; matrix(1,2) =  -4.34;
    matrix(2,0) =   7.95; matrix(2,1) =  -4.34; matrix(2,2) = 242.73;
    return matrix.Invert()*vec_mass*vec_mass;
}
