//### AUTOMATICALLY GENERATED BY src/covarianceMatrixStudy.cpp ###//
//### DATASET: /wk_cms2/youying/public/tH_FCNC/Era2017_RR-31Mar2018_v2/ST_FCNC-TH_Thadronic_HToaa_eta_hct-MadGraph5-pythia8.root
#include <TMatrixD.h>


double Chi2_calculator_simple(double w_mass, double t_mass){
    TVectorD vec_mass(2);
    vec_mass(0) = w_mass - w_boson_mass;
    vec_mass(1) = t_mass - top_quark_mass;
    TMatrixD matrix(2,2);
    matrix(0,0) = 293.63; matrix(0,1) =   0.00;
    matrix(1,0) =   0.00; matrix(1,1) = 750.56;
    return matrix.Invert()*vec_mass*vec_mass;
}

double Chi2_calculator_modified(double w_mass, double t_mass){
    TVectorD vec_mass(2);
    vec_mass(0) = w_mass - w_boson_mass;
    vec_mass(1) = t_mass - top_quark_mass;
    TMatrixD matrix(2,2);
    matrix(0,0) = 293.63; matrix(0,1) = 311.78;
    matrix(1,0) = 311.78; matrix(1,1) = 750.56;
    return matrix.Invert()*vec_mass*vec_mass;
}

double Chi2_calculator_improved(double w_mass, double t_mass, double fcnc_top_mass){
    TVectorD vec_mass(3);
    vec_mass(0) = w_mass - w_boson_mass;
    vec_mass(1) = t_mass - top_quark_mass;
    vec_mass(2) = fcnc_top_mass - top_quark_mass;
    TMatrixD matrix(3,3);
    matrix(0,0) = 293.63; matrix(0,1) = 311.78; matrix(0,2) = -49.90;
    matrix(1,0) = 311.78; matrix(1,1) = 750.56; matrix(1,2) = 286.70;
    matrix(2,0) = -49.90; matrix(2,1) = 286.70; matrix(2,2) = 2318.94;
    return matrix.Invert()*vec_mass*vec_mass;
}
