//### AUTOMATICALLY GENERATED BY src/covarianceMatrixStudy.cpp ###//
//### DATASET: /wk_cms2/youying/public/tH_FCNC/Era2017_RR-31Mar2018_v2/ST_FCNC-TH_Thadronic_HToaa_eta_hut-MadGraph5-pythia8.root
#include <TMatrixD.h>


double Chi2_calculator_simple(double w_mass, double t_mass){
    TVectorD vec_mass(2);
    vec_mass(0) = w_mass - w_boson_mass;
    vec_mass(1) = t_mass - top_quark_mass;
    TMatrixD matrix(2,2);
    matrix(0,0) = 311.16; matrix(0,1) =   0.00;
    matrix(1,0) =   0.00; matrix(1,1) = 783.41;
    return matrix.Invert()*vec_mass*vec_mass;
}

double Chi2_calculator_modified(double w_mass, double t_mass){
    TVectorD vec_mass(2);
    vec_mass(0) = w_mass - w_boson_mass;
    vec_mass(1) = t_mass - top_quark_mass;
    TMatrixD matrix(2,2);
    matrix(0,0) = 311.16; matrix(0,1) = 328.93;
    matrix(1,0) = 328.93; matrix(1,1) = 783.41;
    return matrix.Invert()*vec_mass*vec_mass;
}

double Chi2_calculator_improved(double w_mass, double t_mass, double fcnc_top_mass){
    TVectorD vec_mass(3);
    vec_mass(0) = w_mass - w_boson_mass;
    vec_mass(1) = t_mass - top_quark_mass;
    vec_mass(2) = fcnc_top_mass - top_quark_mass;
    TMatrixD matrix(3,3);
    matrix(0,0) = 311.16; matrix(0,1) = 328.93; matrix(0,2) = -63.03;
    matrix(1,0) = 328.93; matrix(1,1) = 783.41; matrix(1,2) = 247.75;
    matrix(2,0) = -63.03; matrix(2,1) = 247.75; matrix(2,2) = 2311.54;
    return matrix.Invert()*vec_mass*vec_mass;
}
