//### AUTOMATICALLY GENERATED BY src/covarianceMatrixStudy.cpp ###//
//### DATASET: ¥
#include <TMatrixD.h>


double Chi2_calculator_simple(double w_mass, double t_mass){
    TVectorD vec_mass(2);
    vec_mass(0) = w_mass - w_boson_mass;
    vec_mass(1) = t_mass - top_quark_mass;
    TMatrixD matrix(2,2);
    matrix(0,0) = 341.00; matrix(0,1) =   0.00;
    matrix(1,0) =   0.00; matrix(1,1) = 823.95;
    return matrix.Invert()*vec_mass*vec_mass;
}

double Chi2_calculator_modified(double w_mass, double t_mass){
    TVectorD vec_mass(2);
    vec_mass(0) = w_mass - w_boson_mass;
    vec_mass(1) = t_mass - top_quark_mass;
    TMatrixD matrix(2,2);
    matrix(0,0) = 341.00; matrix(0,1) = 370.31;
    matrix(1,0) = 370.31; matrix(1,1) = 823.95;
    return matrix.Invert()*vec_mass*vec_mass;
}

double Chi2_calculator_improved(double w_mass, double t_mass, double fcnc_top_mass){
    TVectorD vec_mass(3);
    vec_mass(0) = w_mass - w_boson_mass;
    vec_mass(1) = t_mass - top_quark_mass;
    vec_mass(2) = fcnc_top_mass - top_quark_mass;
    TMatrixD matrix(3,3);
    matrix(0,0) = 341.00; matrix(0,1) = 370.31; matrix(0,2) =   3.17;
    matrix(1,0) = 370.31; matrix(1,1) = 823.95; matrix(1,2) =   0.83;
    matrix(2,0) =   3.17; matrix(2,1) =   0.83; matrix(2,2) = 250.95;
    return matrix.Invert()*vec_mass*vec_mass;
}
