//### AUTOMATICALLY GENERATED BY src/covarianceMatrixStudy.cpp ###//
#include <TMatrixD.h>
#include "generalChiSquareStudy.h"


double Chi2_calculator_simple(double w_mass, double t_mass){
    TVectorD vec_mass(2);
    vec_mass(0) = w_mass - w_boson_mass;
    vec_mass(1) = t_mass - top_quark_mass;
    TMatrixD matrix(2,2);
    matrix(0,0) = 352.18; matrix(0,1) =   0.00;
    matrix(1,0) =   0.00; matrix(1,1) = 948.97;
    return matrix.Invert()*vec_mass*vec_mass;
}

double Chi2_calculator_modified(double w_mass, double t_mass){
    TVectorD vec_mass(2);
    vec_mass(0) = w_mass - w_boson_mass;
    vec_mass(1) = t_mass - top_quark_mass;
    TMatrixD matrix(2,2);
    matrix(0,0) = 352.18; matrix(0,1) = 379.95;
    matrix(1,0) = 379.95; matrix(1,1) = 948.97;
    return matrix.Invert()*vec_mass*vec_mass;
}

double Chi2_calculator_improved(double w_mass, double t_mass, double fcnc_top_mass){
    TVectorD vec_mass(3);
    vec_mass(0) = w_mass - w_boson_mass;
    vec_mass(1) = t_mass - top_quark_mass;
    vec_mass(2) = fcnc_top_mass - top_quark_mass;
    TMatrixD matrix(3,3);
    matrix(0,0) = 352.18; matrix(0,1) = 379.95; matrix(0,2) =   7.64;
    matrix(1,0) = 379.95; matrix(1,1) = 948.97; matrix(1,2) =  -2.54;
    matrix(2,0) =   7.64; matrix(2,1) =  -2.54; matrix(2,2) = 253.83;
    return matrix.Invert()*vec_mass*vec_mass;
}
