//### AUTOMATICALLY GENERATED BY src/covarianceMatrixStudy.cpp ###//
#include <TMatrixD.h>
#include "generalChiSquareStudy.h"


double Chi2_calculator_simple(double w_mass, double t_mass){
    TVectorD vec_mass(2);
    vec_mass(0) = w_mass - w_boson_mass;
    vec_mass(1) = t_mass - top_quark_mass;
    TMatrixD matrix(2,2);
    matrix(0,0) = 350.70; matrix(0,1) =   0.00;
    matrix(1,0) =   0.00; matrix(1,1) = 981.51;
    return matrix.Invert()*vec_mass*vec_mass;
}

double Chi2_calculator_modified(double w_mass, double t_mass){
    TVectorD vec_mass(2);
    vec_mass(0) = w_mass - w_boson_mass;
    vec_mass(1) = t_mass - top_quark_mass;
    TMatrixD matrix(2,2);
    matrix(0,0) = 350.70; matrix(0,1) = 382.34;
    matrix(1,0) = 382.34; matrix(1,1) = 981.51;
    return matrix.Invert()*vec_mass*vec_mass;
}

double Chi2_calculator_improved(double w_mass, double t_mass, double fcnc_top_mass){
    TVectorD vec_mass(3);
    vec_mass(0) = w_mass - w_boson_mass;
    vec_mass(1) = t_mass - top_quark_mass;
    vec_mass(2) = fcnc_top_mass - top_quark_mass;
    TMatrixD matrix(3,3);
    matrix(0,0) = 350.70; matrix(0,1) = 382.34; matrix(0,2) =   3.05;
    matrix(1,0) = 382.34; matrix(1,1) = 981.51; matrix(1,2) =  -0.67;
    matrix(2,0) =   3.05; matrix(2,1) =  -0.67; matrix(2,2) = 258.01;
    return matrix.Invert()*vec_mass*vec_mass;
}
